[package]
name = "egui_knob_demo"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "egui_knob_demo"
path = "demo.rs"

[dependencies]
egui = "0.30"
egui_knob = "0.1.1"
eframe = { version = "0.30.0", features = ["default_fonts"] }